### ISSUE TITLE
Empty content for all categories

### ISSUE THREAD

**Issue by cjuroz** [lydian/plugin.video.eyny#1]
I am using my eyny user/password with this add-on, I can see all categories like 電影 but when i enter (any category) it shows an empty list:

![image](https://cloud.githubusercontent.com/assets/10542942/23196239/5488ddd4-f8f3-11e6-9927-d3c0e44e0b50.png)

Looks like your parser is broken (most probably because eyny changed something).
Any plan in your side to fix it? Thanks~

**Comment by lydian** [comment]
Thanks for reminding, I just fixed the parser :)

**Comment by cjuroz** [comment]
wow~ so fast! Thanks.
